n$68=_fun___new(sizeof():) [line 1]
*&Bundle:=n$68 [line 2]
n$69=*&Bundle: [line 3]
n$70=_fun___new(sizeof():) [line 4]
_fun_PDPActivity.<init>()(n$70:) [line 5]
*&PDPActivity:=n$70 [line 6]
n$71=*&PDPActivity: [line 7]
_fun_void PDPActivity.onCreate(Bundle)(n$71:,n$69:) virtual [line 8]
_fun_void PDPActivity.onStop()(n$71:) virtual [line 9]
