n$72=_fun___new(sizeof():) [line 1]
*&Bundle:=n$72 [line 2]
n$73=*&Bundle: [line 3]
n$74=_fun___new(sizeof():) [line 4]
_fun_PMPActivity.<init>()(n$74:) [line 5]
*&PMPActivity:=n$74 [line 6]
n$75=*&PMPActivity: [line 7]
_fun_void PMPActivity.onCreate(Bundle)(n$75:,n$73:) virtual [line 8]
_fun_void AppCompatActivity.onStop()(n$75:) virtual [line 9]
n$76=*&#GB$material.com.materialdemo.PMPActivity.InferGeneratedHarness().material.com.materialdemo.MultiTouchListener[line 56]: [line 10]
n$77=_fun___new(sizeof():) [line 11]
*&MotionEvent:=n$77 [line 12]
n$78=*&MotionEvent: [line 13]
n$79=_fun___new(sizeof():) [line 14]
*&View:=n$79 [line 15]
n$80=*&View: [line 16]
n$81=_fun_boolean MultiTouchListener.onTouch(View,MotionEvent)(n$76:,n$80:,n$78:) virtual [line 17]
n$82=*&#GB$material.com.materialdemo.PMPActivity.InferGeneratedHarness().android.view.View$OnClickListener[line 48]: [line 18]
_fun_void PMPActivity$1.onClick(View)(n$82:,n$80:) virtual [line 19]
